<!doctype html>
<html lang="es">
        <?php include "header.php";?>
    <body>
    <div class="main-container">
        <?php include "header2.php";?>
        <section id="slideshow" class="slideshow">
            <?php include "slideshow.php"; ?>
        </section>
    </div> <!-- /.container -->
        <section class="feature-top">
            <?php include "ourproducts.php";?>
        </section>
        <section class="drk-bg pad80">
            <?php include "whoweare.php";?>
        </section>
        <footer>
            <?php include "footer.php";?>
        </footer>
            <?php include "javascripts.php";?>
    </body>
</html>